/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package predatorpreysimulator;

import java.awt.event.ActionEvent;
import predatorpreysimulator.PredatorPreySimulator;

/**
 *
 * @author Sikder Huq
 */
public class SimulationPanel extends javax.swing.JPanel {

    CellPanel[][] grid;
    SimulationFrame simFrame;
    PredatorPreySimulator sim;
    private javax.swing.JSplitPane splitPane;
    int numOfRows, numOfCols, numOfDoodlebugs, numOfAnts;

    /**
     * Creates new form SimulationPanel
     */
    public SimulationPanel(PredatorPreySimulator sim, SimulationFrame sFrame) {
        initComponents();
        this.simFrame = sFrame;
        //this.splitPane.setDividerLocation(280);
        setVisible(true);

        this.sim = sim;
        this.grid = new CellPanel[sim.numOfRows][sim.numOfCols];
        for (int i = 0; i < sim.numOfRows; i++) {
            for (int j = 0; j < sim.numOfCols; j++) {
                this.grid[i][j] = new CellPanel();
                this.simPanel.add(this.grid[i][j]);
            }
        }
        this.simPanel.setLayout(new java.awt.GridLayout(sim.numOfRows, sim.numOfCols, 0, 0));
        sim.setGrid(this.grid);
        sim.initWorld();

        setLabels();
    }

    void setLabels() {
        this.timeStepLabel.setText("Time step: " + this.sim.timeStep);
        this.timeStepLabel.setText("Number of ants: " + this.sim.numOfAnts);
        this.bugsLabel.setText("Number of bugs: " + this.sim.numOfBugs);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        simPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        timeStepLabel = new javax.swing.JLabel();
        antsLabel = new javax.swing.JLabel();
        bugsLabel = new javax.swing.JLabel();
        NextButton = new javax.swing.JButton();

        simPanel.setLayout(null);
        jScrollPane1.setViewportView(simPanel);

        timeStepLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        timeStepLabel.setForeground(new java.awt.Color(0, 102, 255));

        antsLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        bugsLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(antsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(timeStepLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(bugsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(timeStepLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(antsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bugsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        NextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/next.png"))); // NOI18N
        NextButton.setText("Next Step");
        NextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(NextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(NextButton)
                .addContainerGap(353, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void NextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButtonActionPerformed
        this.sim.goNext();
        setLabels();
        for (int i = 0; i < this.sim.numOfRows; i++) {
            for (int j = 0; j < this.sim.numOfCols; j++) {
                final int row = i;
                final int col = j;

                javax.swing.Timer t = new javax.swing.Timer(500, new java.awt.event.ActionListener() {
                    public void actionPerformed(ActionEvent e) {
                        SimulationPanel.this.grid[row][col].setBackground(InitPanel.gridBgColor);
                    }

                });
                t.setRepeats(false);
                t.start();
            }
        }
    }//GEN-LAST:event_NextButtonActionPerformed
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NextButton;
    private javax.swing.JLabel antsLabel;
    private javax.swing.JLabel bugsLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel simPanel;
    private javax.swing.JLabel timeStepLabel;
    // End of variables declaration//GEN-END:variables
}
